title: Sanghamitra Sengupta
description: Hazards Geographer | MS
theme: jekyll-theme-architect
#logo: /assets/logo.png # Optional
author: Sanghamitra Sengupta
email: ssngpta1@memphis.edu
github_username: sanghamitra-sengupta
#linkedin: https://www.linkedin.com/in/sanghamitra-sengupta/


